create database social_media
use social_media

CREATE TABLE USERS(
       ID INT IDENTITY PRIMARY KEY,
	   EMAIL VARCHAR(100) UNIQUE,
	   USERNAME VARCHAR(50) UNIQUE,
	   JOINTDATE DATE DEFAULT GETUTCDATE(),
	   GENDER   VARCHAR(6) CHECK (GENDER IN ('MALE','FEMALE')),
	   DATE_OF_BIRTH VARCHAR(10)

);

CREATE TABLE COMMENT(
      COMMENT_ID INT IDENTITY PRIMARY KEY,
	  CONTENT VARCHAR(100),
	  COMMENT_DATE DATE DEFAULT GETUTCDATE(),
	  USER_ID INT FOREIGN KEY  REFERENCES  USERS(ID)  
	

);

CREATE TABLE POST(
      POST_ID INT IDENTITY PRIMARY KEY,
	   USER_ID INT FOREIGN KEY REFERENCES USERS (ID), 
	   CONTENT VARCHAR(100),
	   POST_DATE DATE DEFAULT GETUTCDATE(),
	   [PUBLIC] BIT,
	   [PRIVATE] BIT
	   
);
 CREATE TABLE INTERACT(
     USER_ID INT FOREIGN KEY  REFERENCES USERS (ID), 
	 POST_ID INT  FOREIGN KEY  REFERENCES POST (POST_ID),
	 PRIMARY KEY(USER_ID,POST_ID),
	 
 );

 CREATE TABLE INTERACTION(
      INTERACTION_ID INT IDENTITY PRIMARY KEY,
	  USER_ID INT FOREIGN KEY  REFERENCES USERS (ID),
	 POST_ID INT FOREIGN KEY  REFERENCES POST (POST_ID),
	 INTERACTION_DATE DATE DEFAULT GETUTCDATE(),
	 TYPE VARCHAR(100)
	
	 
 );


INSERT INTO USERS (EMAIL, USERNAME, JOINTDATE, GENDER, DATE_OF_BIRTH)
VALUES 
    ('user1@example.com', 'UserOne', GETUTCDATE(), 'MALE', '2000-05-10'),
    ('user2@example.com', 'UserTwo', GETUTCDATE(), 'FEMALE', '1998-08-22');
INSERT INTO POST (USER_ID, CONTENT, POST_DATE, [PUBLIC], [PRIVATE])
VALUES 
    (1, 'UserOne first post', GETUTCDATE(), 1, 0),
    (2, 'UserTwo private post', GETUTCDATE(), 0, 1);

INSERT INTO COMMENT (CONTENT, COMMENT_DATE, USER_ID)
VALUES 
    ('This is the first comment', GETUTCDATE(), 1),
    ('Another comment from user2', GETUTCDATE(), 2);

INSERT INTO INTERACT (USER_ID, POST_ID)
VALUES 
    (1, 1),  
    (2, 2);
	INSERT INTO INTERACTION (USER_ID, POST_ID, INTERACTION_DATE, TYPE)
VALUES 
    (1, 1, GETUTCDATE(), 'LIKE'),  
    (2, 2, GETUTCDATE(), 'COMMENT');


	DROP TABLE USERS   /* CANNOT DROp AS ITS ID USED IN OTHER TABLES*/
	DROP DATABASE social_media 